S11/discussion/discussion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todolist/', include('todolist.urls')),
    path('admin/', admin.site.urls),
]

S11/discussion/todolist/urls.py
from django.urls import path
from . import views


# Syntax
# path(route, view, name)
app_name = 'todolist'
urlpatterns = [
	path('', views.index, name='index'),
	#/todolist/<todoitem_id>
	#/todolist/1
	# The <int:todoitem_id> allows for creating a dynamic link where the todoitem_id is provided
	path('<int:todoitem_id>/', views.todoitem, name='viewtodoitem'),
	# /todolist/register
	path('register', views.register_user, name='register'),
	path('change_password', views.change_password, name="change_password"),
	path('login', views.login_user, name="login"),
	path('logout', views.logout_view, name="logout"),
	path('add_event', views.add_event, name="add_event"),
]

S11/discussion/todolist/models.py
from django.db import models
from django import forms
from django.contrib.auth.models import User
# Create your models here.

class ToDoItem(models.Model):
	task_name = models.CharField(max_length=50)
	description = models.CharField(max_length=200)
	status = models.CharField(max_length=50, default="pending")
	date_created = models.DateTimeField('date created')
 
class RegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password_repeat = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    
class EventForm(forms.Form):
    event_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    description = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    date_created = forms.DateTimeField(widget=forms.SelectDateWidget())
    
class EventItem(models.Model):
    event_name = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    status = models.CharField(max_length=50, default="pending")
    date_stretch = models.DateTimeField('date stretch')
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)

S11/discussion/todolist/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
# from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.forms.models import model_to_dict
from django.http import HttpResponseRedirect

from .models import ToDoItem, RegisterForm, LoginForm, EventItem, EventForm

def index(request):
	todoitem_list = ToDoItem.objects.all()
	eventitem_list = EventItem.objects.all()
	context = {
		'todoitem_list': todoitem_list,
		'eventitem_list': eventitem_list,
		'user': request.user
		}

	return render(request, "todolist/index.html", context)

	# template = loader.get_template("todolist/index.html")
	# context = {
	# 	'todoitem_list': todoitem_list
	# }
	# return HttpResponse(template.render(context, request))

	# output = ', '.join([todoitem.task_name for todoitem in todoitem_list])
	# return HttpResponse(output)
	# return HttpResponse("Hello from the views.py file")

def todoitem(request, todoitem_id):
	
	todoitem = model_to_dict(ToDoItem.objects.get(pk=todoitem_id))

	return render(request, "todolist/todoitem.html", todoitem)


	# response = "You are viewing the details of %s"
	# return HttpResponse(response % todoitem_id)

def register_user(request):
    # if this is a POST request we need to process the form data
    template = 'todolist/register.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = RegisterForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            if User.objects.filter(username=form.cleaned_data['username']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Username already exists.'
                })
            elif User.objects.filter(email=form.cleaned_data['email']).exists():
                return render(request, template, {
                    'form': form,
                    'error_message': 'Email already exists.'
                })
            elif form.cleaned_data['password'] != form.cleaned_data['password_repeat']:
                return render(request, template, {
                    'form': form,
                    'error_message': 'Passwords do not match.'
                })
            else:
                # Create the user:
                user = User.objects.create_user(
                    form.cleaned_data['username'],
                    form.cleaned_data['email'],
                    form.cleaned_data['password']
                )
                user.first_name = form.cleaned_data['first_name']
                user.last_name = form.cleaned_data['last_name']
                user.save()
               
                # Login the user
                login(request, user)
                # return redirect("index")
                # redirect to accounts page:
                context = {
					"is_user_authenticated": True
				}
                return render(request, "todolist/index.html", context)
				

   # No post data availabe, let's just show the page.
    else:
        form = RegisterForm()

    return render(request, template, {'form': form})


def register(request):
	users = User.objects.all()
	is_user_registered = False
	context = {
	"is_user_registered": is_user_registered
	}

	for indiv_user in users:
		if indiv_user.username == "johndoe":
			is_user_registered = True
			break

	if is_user_registered == False:
		user = User()
		user.username = "johndoe"
		user.first_name = "John"
		user.last_name = "Doe"
		user.email = "john@mail.com"
		# user.password = "john1234"
		# The set_password method is used to ensure that the password is hashed
		user.set_password("john1234")
		user.is_staff = False
		user.is_active = True
		user.save()
		context = {
			"first_name": user.first_name,
			"last_name": user.last_name
		}


	return render(request, "todolist/register.html", context)


def change_password(request):
# if this is a POST request we need to process the form data
    template = 'todolist/login.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
    
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                context = {
					"is_user_authenticated": True
				}
                return render(request, "todolist/index.html", context)

    else:
        form = LoginForm()

    return render(request, template, {'form': form})

def login_user(request):
    # if this is a POST request we need to process the form data
    template = 'todolist/login.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = LoginForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
    
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request, user)
                context = {
					"is_user_authenticated": True
				}
                return render(request, "todolist/index.html", context)

    else:
        form = LoginForm()

    return render(request, template, {'form': form})

def logout_view(request):
	logout(request)
	context = {
		"is_user_authenticated": False
	}
	# return render(request, "todolist/index.html", context)
	return render(request, "todolist/index.html", context)

def update_user(request):
    return request


def add_event(request):
    # if this is a POST request we need to process the form data  
    template = 'todolist/add_event.html'
   
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = EventForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
    
            event_name = form.cleaned_data['event_name']
            desc = form.cleaned_data['description']
            date_pick = form.cleaned_data['date_created']
            event = EventItem(event_name = event_name, description = desc, date_stretch = date_pick, user_id = request.user)
            event.save()
            return render(request, "todolist/index.html")
                

    else:
        form = EventForm()

    return render(request, template, {'form': form})

S11/discussion/todolist/templates/todolist/add_event.html
{% extends "todolist/base.html" %}

{% block content %}

	{% if is_user_registered == False %}
		<h1>Duplicate User Found!</h1>
		<p>A duplicate user has been found, user creation unsuccessful</p>
	{% else %}
		<div class="container">
			<form action="{% url 'todolist:add_event' %}" method="post">
				{% csrf_token %}
				<div class="col-md-8 col-md-offset-2">
					<div class="panel panel-default">
						<div class="panel-heading">Create Event</div>
						<div class="panel-body">
							{% if error_message %}
								<p class="bg-danger p-d ml-b">{{ error_message }}</p>
							{% endif %}
							<div class="form-group clearfix">
								<label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Event Name<span class="text-red"></span>:</label>
								<div class="col-md-6">
									{{ form.event_name }}
								</div>
							</div>
							<div class="form-group clearfix">
								<label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Description<span class="text-red">*</span>:</label>
								<div class="col-md-6">
									{{ form.description }}
								</div>
							</div>
                            <div class="form-group clearfix">
								<label for="{{ form.date.id_for_label }}" class="col-md-4 control-label text-right">Stretch Date<span class="text-red">*</span>:</label>
								<div class="col-md-6">
									{{ form.date_created }}
								</div>
							</div>
							<div class="col-md-6 col-md-offset-4">
								<input type="submit" value="Add Event" class="btn btn-success">
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	{% endif %}

{% endblock %}

S11/discussion/todolist/templates/todolist/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>To Do List</title>
   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
   
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body class="override">
    <nav class="navbar navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/mymodule/">To Do List</a>
            </div>
           
            <div id="navbar" class="collapse navbar-collapse">
                {% if user.is_authenticated == True%}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="logout">Logout</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a>Change Acc Pass</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a>Change User Details</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a>{{ user.first_name }}</a></li>
                    </ul>
                {% else %}
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/todolist/register">Register</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/todolist/login">Login</a></li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </nav>
   
    <div class="container">
        <div class="row">
            {% block content %}{% endblock %}
        </div>
    </div>
</body>
</html>

S11/discussion/todolist/templates/todolist/change_password.html
{% if is_user_authenticated == False %}
	<h1>Invalid User Credentials</h1>
	<p>Check if the username and password is correct.</p>

{% else %}
	<h1>User Password Successfully Updated!</h1>
	<p>The password has been successfully updated.</p>

{% endif %}

S11/discussion/todolist/templates/todolist/index.html
{% extends "todolist/base.html" %}

{%block content%}

	{% if user.is_authenticated == True %}
		<h1>Welcome {{user.first_name}} {{user.last_name}}!</h1>
		<ul>
			<h3>Items</h3>
		{%if todoitem_list.count != 0%}
			{% for todoitem in todoitem_list %}
				<li>
					<a href="{{todoitem.id}}">{{todoitem.task_name}}</a>
				</li>
			{% endfor %}
		{%else%}
			<p>No tasks have been created.</p>
		{% endif %}

		{%if eventitem_list.count != 0%}
			<h3>Events</h3>
			{% for eventitem in eventitem_list %}
				<li>
					<a href="{{eventitem.id}}">{{eventitem.event_name}}</a>
				</li>
			{% endfor %}
		{%else%}
			<p>No event have been created.</p>
		{% endif %}		

			<a class="btn btn-primary" href="add_event">Add Event</a>
		</ul>		
	{% else %}
		<h1>You are not authorized to access this page.</h1>
		<p>Kindly login <a href="login">here</a></p>
	{% endif %}

{% endblock %}

S11/discussion/todolist/templates/todolist/login.html
{% extends "todolist/base.html" %}

{% block content %}

	{% if is_user_registered == False %}
		<h1>Duplicate User Found!</h1>
		<p>A duplicate user has been found, user creation unsuccessful</p>
	{% else %}
		<div class="container">
			<form action="{% url 'todolist:login' %}" method="post">
				{% csrf_token %}
				<div class="col-md-8 col-md-offset-2">
					<div class="panel panel-default">
						<div class="panel-heading">Login</div>
						<div class="panel-body">
							{% if error_message %}
								<p class="bg-danger p-d ml-b">{{ error_message }}</p>
							{% endif %}
							<div class="form-group clearfix">
								<label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Username<span class="text-red"></span>:</label>
								<div class="col-md-6">
									{{ form.username }}
								</div>
							</div>
							<div class="form-group clearfix">
								<label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
								<div class="col-md-6">
									{{ form.password }}
								</div>
							</div>
							<div class="col-md-6 col-md-offset-4">
								<input type="submit" value="Login" class="btn btn-success">
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	{% endif %}

{% endblock %}

S11/discussion/todolist/templates/todolist/register.html
{% extends "todolist/base.html" %}

{% block content %}

	{% if is_user_registered == False %}
		<h1>Duplicate User Found!</h1>
		<p>A duplicate user has been found, user creation unsuccessful</p>
	{% else %}
		<div class="container">
			<form action="{% url 'todolist:register' %}" method="post">
				{% csrf_token %}
				<div class="col-md-8 col-md-offset-2">
					<div class="panel panel-default">
						<div class="panel-heading">Register</div>
						<div class="panel-body">
							{% if error_message %}
								<p class="bg-danger p-d ml-b">{{ error_message }}</p>
							{% endif %}
							<div class="form-group clearfix">
								<label for="{{ form.first_name.id_for_label }}" class="col-md-4 control-label text-right">First Name:</label>
								<div class="col-md-6">
									{{ form.first_name }}
								</div>
							</div>
							<div class="form-group clearfix">
								<label for="{{ form.last_name.id_for_label }}" class="col-md-4 control-label text-right">Last Name:</label>
								<div class="col-md-6">
									{{ form.last_name }}
								</div>
							</div>
							<div class="form-group clearfix">
								<label for="{{ form.username.id_for_label }}" class="col-md-4 control-label text-right">Username<span class="text-red">*</span>:</label>
								<div class="col-md-6">
									{{ form.username }}
								</div>
							</div>
							<div class="form-group clearfix">
								<label for="{{ form.email.id_for_label }}" class="col-md-4 control-label text-right">Email<span class="text-red">*</span>:</label>
								<div class="col-md-6">
									{{ form.email }}
								</div>
							</div>
							<div class="form-group clearfix">
								<label for="{{ form.password.id_for_label }}" class="col-md-4 control-label text-right">Password<span class="text-red">*</span>:</label>
								<div class="col-md-6">
									{{ form.password }}
								</div>
							</div>
							<div class="form-group clearfix">
								<label for="{{ form.password_repeat.id_for_label }}" class="col-md-4 control-label text-right">Confirm password:</label>
								<div class="col-md-6">
									{{ form.password_repeat }}
								</div>
							</div>
							<div class="col-md-6 col-md-offset-4">
								<input type="submit" value="Register" class="btn btn-success">
							</div>
						</div>
					</div>
				</div>
			</form>
		</div>
	{% endif %}

{% endblock %}

S11/discussion/todolist/templates/todolist/todoitem.html
<h1>{{task_name}}</h1>
<h3>Description</h3>
<p>{{description}}</p>
<h3>Status</h3>
<p>{{status}}</p>
<a href="../">Back to index page.</a>